import type { Dish, Category, StoreSettings } from '@/types'

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-makis',
    name: 'Makis',
    slug: 'makis',
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-rolls',
    name: 'Rolls Especiales',
    slug: 'rolls-especiales',
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-ceviches',
    name: 'Ceviches',
    slug: 'ceviches',
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-tiraditos',
    name: 'Tiraditos',
    slug: 'tiraditos',
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-bebidas',
    name: 'Bebidas',
    slug: 'bebidas',
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-postres',
    name: 'Postres',
    slug: 'postres',
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
]

export const MOCK_DISHES: (Dish & { category?: Category; categories?: Category })[] = [
  {
    id: 'dish-acevichado',
    category_id: 'cat-makis',
    name: 'Acevichado Roll',
    description: 'Relleno de langostino al panko y palta fresca, cubierto con láminas de atún y nuestra salsa acevichada artesanal con shichimi togarashi.',
    price: 32.0,
    image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 1,
    discount_percentage: 15,
    is_popular: true,
    is_promoted: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    categories: MOCK_CATEGORIES[0],
  },
  {
    id: 'dish-furai',
    category_id: 'cat-makis',
    name: 'Furai Maki (Crocante)',
    description: 'Roll empanizado al panko y frito a punto crujiente, relleno de salmón fresco, queso crema philadelphia y palta, con salsa tare dulce.',
    price: 28.0,
    image_url: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 2,
    discount_percentage: 0,
    is_popular: true,
    is_promoted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    categories: MOCK_CATEGORIES[0],
  },
  {
    id: 'dish-lomo',
    category_id: 'cat-rolls',
    name: 'Lomo Saltado Nikkei Roll',
    description: 'Fusión insignia: relleno de palta y queso crema, cubierto con finas tiras de lomo flambeado al wok con cebolla morada, tomate y reducción de soya.',
    price: 35.0,
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 3,
    discount_percentage: 10,
    is_popular: true,
    is_promoted: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    categories: MOCK_CATEGORIES[1],
  },
  {
    id: 'dish-avocado-passion',
    category_id: 'cat-rolls',
    name: 'Avocado Passion Roll',
    description: 'Langostinos tempura y queso crema, envuelto en palta hass madura y coronado con reducción de maracuyá y semillas de ajonjolí tostado.',
    price: 30.0,
    image_url: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 4,
    discount_percentage: 20,
    is_popular: false,
    is_promoted: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
    categories: MOCK_CATEGORIES[1],
  },
  {
    id: 'dish-ceviche-nikkei',
    category_id: 'cat-ceviches',
    name: 'Ceviche Clásico Nikkei',
    description: 'Cubos de pescado blanco del día marinados en leche de tigre al ají amarillo y toques de kion y shoyu, servido con camote glaseado y choclo tierno.',
    price: 38.0,
    image_url: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 5,
    discount_percentage: 0,
    is_popular: true,
    is_promoted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
    categories: MOCK_CATEGORIES[2],
  },
  {
    id: 'dish-tiradito-salmon',
    category_id: 'cat-tiraditos',
    name: 'Tiradito de Salmón al Ají Amarillo',
    description: 'Láminas finas de salmón atlántico bañadas en cremosa emulsión de ají amarillo y lima, con gotas de aceite de ajonjolí y chalaquita crocante.',
    price: 36.0,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 6,
    discount_percentage: 15,
    is_popular: false,
    is_promoted: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
    categories: MOCK_CATEGORIES[3],
  },
  {
    id: 'dish-maracuya',
    category_id: 'cat-bebidas',
    name: 'Infusión Maracuyá Nikkei',
    description: 'Bebida artesanal refrescante de pulpa natural de maracuyá con hierbaluisa aromática y un toque sutil de kion.',
    price: 12.0,
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 7,
    discount_percentage: 0,
    is_popular: false,
    is_promoted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
    categories: MOCK_CATEGORIES[4],
  },
  {
    id: 'dish-mochi-matcha',
    category_id: 'cat-postres',
    name: 'Mochi Helado Matcha & Maracuyá',
    description: 'Suaves bocados japoneses de masa de arroz rellenos de helado cremoso de té verde matcha y sorbete de maracuyá (3 unidades).',
    price: 18.0,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop',
    is_available: true,
    sort_order: 8,
    discount_percentage: 0,
    is_popular: true,
    is_promoted: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[5],
    categories: MOCK_CATEGORIES[5],
  },
]

export const MOCK_STORE_SETTINGS: StoreSettings = {
  id: 'store-settings-default',
  is_open: true,
  open_days: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'],
  open_time: '12:00',
  close_time: '22:00',
  allows_reservations: true,
  delivery_enabled: true,
  phone: '+51 987 654 321',
  whatsapp: '+51 987 654 321',
  email: 'contacto@makibros.me',
  address: 'Av. Dos de Mayo 850, San Isidro, Lima',
  tiktok_url: 'https://www.tiktok.com/@makibros.of',
  instagram_url: 'https://www.instagram.com/makibros.of',
  facebook_url: 'https://www.facebook.com/makibros.of',
  about_text:
    'MakiBros — Fusión peruano-japonesa que despierta tus sentidos. Nuestros makis, rolls especiales, ceviches y tiraditos están hechos con ingredientes frescos y la pasión de combinar lo mejor de la gastronomía peruana y japonesa.',
  hero_image_url: null,
  updated_at: new Date().toISOString(),
}
